version: '3.7'

services:
  front:
    build:
        context: frontend
        dockerfile: Dockerfile
        target: prod
    networks:
        - internal
    depends_on:
      - back
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf

  back:
    environment:
      - CORS_URL=https://ilmo.io
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - internal
    depends_on:
      - mongodb
    command: sh -c './wait-for mongodb:27017 -- npm start'

  mongodb:
    hostname: mongodb
    image: mongo:4.4.0
    logging:
      driver: none
    volumes:
      - ./data/db:/data/db
    networks:
        - internal
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: mongod --replSet "rs0"

  caddy:
    image: caddy:2.2.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
        - internal

volumes:
  caddy_data:
  caddy_config:

networks:
  internal:
